language: python
python:
  - "3.7"

before_install:
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

install:
  - conda env update -f environment.yml
  - conda activate aquatx-srna

script:
  - python -m unittest tests.unit_tests_entry
  - python -m unittest tests.unit_tests_collapser
  - python -m unittest tests.unit_tests_counter
  - python -m unittest tests.unit_tests_hts_parsing
