name: aquatx-srna
channels:
  - bioconda
dependencies:
  - python>=3.7
  - numpy==1.19.2
  - pandas==1.2.1
  - matplotlib==3.3.2
  - fastp==0.20.1
  - bowtie>=1.2.3
  - tbb==2020.3  # Bowtie dependency, temporary fix. v2021.x breaks bowtie, is not properly pinned to v2020 in bioconda
  - nodejs>=10.13.0
  - pip
  - pip:
      - htseq
      - psutil
      - "toil[cwl]"
      - boto
      - boto3
      - . # This allows pip to handle the installation of AQuATx via setup.py