name: tinyrna
channels:
  - bioconda
dependencies:
  - python>=3.7
  - numpy==1.19.2
  - pandas==1.2.4
  - conda-forge::matplotlib==3.4.3
  - fastp==0.22.0
  - bowtie==1.2.3
  - tbb==2020.3  # Bowtie dependency, temporary fix. v2021.x breaks bowtie, is not properly pinned to v2020 in bioconda
  - nodejs==10.13.0
  - conda-forge::cwltool==3.1.20211001174446
  - conda-forge::psutil==5.8.0
  - conda-forge::mscorefonts==0.0.1
  - setuptools==52.0.0
  - pip==21.2.4
  - pip:
    - --use-feature=in-tree-build
    - htseq==0.13.5
    - . # Install tinyRNA via setup.py