######----------------------------- tinyRNA Configuration -----------------------------######
#
# In this file you can specify your configuration preferences for the workflow.
#
# If you want to use DEFAULT settings for the workflow, all you need to do is provide the path
# to your Samples Sheet and Features Sheet in your Paths File, then make sure that the
# 'paths_config' setting below points to your Paths File.
#
# We suggest that you also:
#   1. Add a `user` below to identify the person performing runs.
#   2. Add a `run_name` below to prefix your run directory and summary reports.
#      If not provided, user_tinyrna is used.
#
# This file will be processed at run time to generate the appropriate settings
# for each workflow step. A copy of the processed configuration will be saved
# in your run directory for auto-documentation.
#
######-------------------------------------------------------------------------------######

user:
run_date: ~
run_time: ~
paths_config: ./paths.yml

##-- The label for final outputs --##
##-- If none provided, the default of user_tinyrna will be used --##
run_name:

##-- Number of threads to use when a step supports multi-threading --##
##-- For best performance, this should be equal to your computer's processor core count --##
threads: 4

##-- Control the amount of information printed to terminal: debug, normal, quiet --##
verbosity: normal

##-- If True: process fastp, tiny-collapse, and bowtie in parallel per-library --##
run_parallel: true

##-- (EXPERIMENTAL) If True: execute the pipeline using native cwltool Python --##
run_native: false

######------------------------- BOWTIE INDEX BUILD OPTIONS --------------------------######
#
# If you do not already have bowtie indexes, they can be built for you by setting
# run_bowtie_build (above) to true and adding your reference genome file(s) to your
# paths_config file.
#
# We have specified default parameters for small RNA data based on our own "best practices".
# You can change the parameters here.
#
######-------------------------------------------------------------------------------######


##-- SA is sampled every 2^offRate BWT chars (default: 5)
offrate: ~

##-- Convert Ns in reference to As --##
ntoa: false

##-- Don't build .3/.4.ebwt (packed reference) portion --##
noref: false

##-- Number of chars consumed in initial lookup (default: 10) --##
ftabchars: ~


######---------------------TRIMMING AND QUALITY FILTER OPTIONS ----------------------######
#
# We use the program fastp to perform: adapter trimming (req), quality filtering (on),
# and QC analysis for an output QC report. See https://github.com/OpenGene/fastp for more
# information on the fastp tool. We have limited the options available to those appropriate
# for small RNA sequencing data. If you require an addition option, create an issue on the
# pipeline github: https://github.com/MontgomeryLab/tinyrna
#
# We have specified default parameters for small RNA data based on our own "best practices".
# You can change the parameters here.
#
######-------------------------------------------------------------------------------######


##-- Adapter sequence to trim --##
adapter_sequence: 'auto'

##-- Minumum & maximum accepted lengths after trimming --##
length_required: 15
length_limit: 35

##-- Minimum average score for a read to pass quality filter --##
average_qual: 25

##-- Minimum phred score for a base to pass quality filter --##
qualified_quality_phred: 20

##-- Minimum % of bases that can be below minimum phred score (above) --##
unqualified_percent_limit: 10

##-- Minimum allowed number of bases --##
n_base_limit: 1

##-- Compression level for gzip output --##
compression: 4

###-- Unused optional inputs: Remove '#' in front to use --###
##-- Trim poly x tails of a given length --##
# trim_poly_x: false
# poly_x_min_len: 0

##-- Trim n bases from the front/tail of a read --##
# trim_front1: 0
# trim_tail1: 0

##-- Is the data phred 64? --##
# fp_phred64: False

##-- Turn on overrepresentation sampling analysis --##
# overrepresentation_sampling: 0
# overrepresentation_analysis: false

##-- If true: don't overwrite the files --##
# dont_overwrite: false

##-- If true: disable these options --##
# disable_quality_filtering: false
# disable_length_filtering: false
# disable_adapter_trimming: false


######--------------------------- READ COLLAPSER OPTIONS ----------------------------######
#
# We use a custom Python utility for collapsing duplicate reads.
# We recommend using the default (keep all reads, or threshold: 0).
# Sequences <= threshold will not be included in downstream steps.
# Trimming takes place prior to counting/collapsing.
#
# We have specified default parameters for small RNA data based on our own "best practices".
# You can change the parameters here.
#
######-------------------------------------------------------------------------------######

##-- Trim the specified number of bases from the 5' end of each sequence --##
5p_trim: 0

##-- Trim the specified number of bases from the 3' end of each sequence --##
3p_trim: 0

##-- Sequences with count <= threshold will be placed in a separate low_counts fasta --##
threshold: 0

##-- If True: outputs will be gzip compressed --##
compress: False


######-------------------------- BOWTIE ALIGNMENT OPTIONS ---------------------------######
#
# We use bowtie for read alignment to a genome.
#
# We have specified default parameters for small RNA data based on our own "best practices".
# You can change the parameters here.
#
######-------------------------------------------------------------------------------######


##-- Report end-to-end hits w/ <=v mismatches; ignore qualities (option -v) --##
end_to_end: 0

##-- Report all alignments per read (much slower than low -k) (option --all) --##
all_aln: True

##-- Seed for random number generator (option --seed) --##
seed: 0

##-- Suppress SAM records for unaligned reads (option --no-unal) --##
no_unal: True

##-- Use shared mem for index; many bowtie's can share (option --shmem) --##
##-- Note: this requires further configuration of your OS --##
##-- http://bowtie-bio.sourceforge.net/manual.shtml#bowtie-options-shmem --##
shared_memory: False

###-- Unused option inputs: Remove '#' in front to use --###
##-- Hits are guaranteed best stratum, sorted; ties broken by quality (option --best) --##
#best: False

##-- Hits in sub-optimal strata aren't reported (requires best, ^^^^) (option --strata) --##
#strata: False

##-- Max mismatches in seed (can be 0-3, default: -n 2) (option --seedmms) --##
#seedmms: 2

##-- Seed length for seedmms (default: 28) (option --seedlen) --##
#seedlen: 28

##-- Do not align to forward/reverse-complement reference strand (options --norc and --nofw) --##
#norc: False
#nofw: False

##-- Input quals are Phred+64 (same as --solexa1.3-quals) (option --phred64-quals) --##
#bt_phred64: False

##-- Report up to <int> good alignments per read (default: 1) (option -k) --##
#k_aln

##-- Suppress all alignments if > <int> exist (default: no limit) (option -m) --##
#suppress_aln: 10

##-- Trim <int> bases from 5' (left) or 3' (right) end of reads (options --trim5 and --trim3) --##
#trim5: 0
#trim3: 0

##-- Input quals are from GA Pipeline ver. < 1.3 (option --solexa-quals) --##
#solexa: false

##-- Input quals are from GA Pipeline ver. >= 1.3 (option --solexa1.3-quals) --##
#solexa13: false


######--------------------------- FEATURE COUNTER OPTIONS ---------------------------######
#
# We use a custom Python utility that utilizes HTSeq's Genomic Array of Sets and GFF reader
# to count small RNA reads. Selection rules are defined in your Features Sheet.
#
######-------------------------------------------------------------------------------######


##-- If True: show all parsed features in the counts csv, regardless of count/identity --##
counter_all_features: False

##-- If True: counts will be normalized by genomic hits AND selected feature count --##
##-- If False: counts will only be normalized by genomic hits --##
counter_normalize_by_hits: True

##-- If True: a decollapsed copy of each SAM file will be produced (useful for IGV) --##
counter_decollapse: False

##-- Select the StepVector implementation that is used. Options: HTSeq or Cython --##
counter_stepvector: 'Cython'

##-- If True: produce alignment tables and assignment diagnostics for uncounted reads --##
counter_diags: False


######--------------------------- DIFFERENTIAL EXPRESSION ---------------------------######
#
# Differential expression analysis is performed using the DESeq2 R library.
#
######-------------------------------------------------------------------------------######


##-- If True: produce a principal component analysis plot from the input dataset --##
dge_pca_plot: True

##-- If True: before analysis, drop features which have a zero count across all samples --##
dge_drop_zero: False


######-------------------------------- PLOTTING OPTIONS -----------------------------######
#
# We use a custom Python script for creating all plots. If you wish to use another matplotlib
# stylesheet you can specify that in the Paths File.
#
# We have specified default parameters for small RNA data based on our own "best practices".
# You can change the parameters here.
#
######-------------------------------------------------------------------------------######


##-- Enable plots by uncommenting (removing the '#') for the desired plot type --##
##-- Disable plots by commenting (adding a '#') for the undesired plot type --##
plot_requests:
  - 'len_dist'
  - 'rule_charts'
  - 'class_charts'
  - 'replicate_scatter'
  - 'sample_avg_scatter_by_dge'
  - 'sample_avg_scatter_by_dge_class'

##-- You can set a custom P value to use in DGE scatter plots. Default: 0.05 --##
plot_pval: ~

##-- If True: scatter plot points will be vectorized. If False, only points are raster --##
plot_vector_points: False

##-- Optionally set the min and/or max lengths for len_dist plots; auto if unset --##
plot_len_dist_min:
plot_len_dist_max:

##-- Optionally set the log2 min and/or max view limits for scatter_by_dge plots; auto if unset --##
plot_dge_scatter_min:
plot_dge_scatter_max:

##-- Use this label in class plots for counts assigned by rules lacking a classifier --##
plot_unknown_class: "_UNKNOWN_"

##-- Use this label in class plots for unassigned counts --##
plot_unassigned_class: "_UNASSIGNED_"

##-- Optionally filter the classes in class scatter plots --##
plot_class_scatter_filter:
  style: include  # Choose: include or exclude
  classes: []     # Add classes between [ and ], separated by comma


######----------------------------- OUTPUT DIRECTORIES ------------------------------######
#
# Outputs for each step are organized into their own subdirectories in your run
# directory. You can set these folder names here.
#
######-------------------------------------------------------------------------------######


dir_name_bt_build: bowtie-build
dir_name_fastp: fastp
dir_name_tiny-collapse: tiny-collapse
dir_name_bowtie: bowtie
dir_name_tiny-count: tiny-count
dir_name_tiny-deseq: tiny-deseq
dir_name_tiny-plot: tiny-plot
dir_name_logs: logs


#########################  AUTOMATICALLY GENERATED CONFIGURATIONS #########################
#
# Do not make any changes to the following sections. These options are automatically
# generated using your Paths File, your Samples and Features sheets, and the above
# settings in this file.
#
###########################################################################################

version: 1.3.0

######--------------------------- DERIVED FROM PATHS FILE ---------------------------######
#
# The following configuration settings are automatically derived from the Paths File
#
######-------------------------------------------------------------------------------######

run_directory: ~
tmp_directory: ~
features_csv: { }
samples_csv: { }
paths_file: { }
gff_files: [ ]
run_bowtie_build: false
reference_genome_files: [ ]
plot_style_sheet: ~
adapter_fasta: ~
ebwt: ~


######------------------------- DERIVED FROM SAMPLES SHEET --------------------------######
#
# The following configuration settings are automatically derived from the Samples Sheet
#
######-------------------------------------------------------------------------------######

##-- Utilized by fastp, tiny-collapse, and bowtie --##
sample_basenames: [ ]

##-- Utilized by fastp --##
# input fastq files
in_fq: [ ]
# output reports
fastp_report_titles: [ ]

###-- Utilized by bowtie --###
# bowtie index files
bt_index_files: [ ]

##-- Utilized by tiny-deseq.r --##
# The control for comparison. If unspecified, all comparisons are made
control_condition:
# If the experiment design yields less than one degree of freedom, tiny-deseq.r is skipped
run_deseq: True

######------------------------- DERIVED FROM FEATURES SHEET -------------------------######
#
# The following configuration settings are automatically derived from the Features Sheet
#
######-------------------------------------------------------------------------------######



######--------------------------- DERIVED FROM RUN CONFIG ---------------------------######
#
# The following configuration settings are automatically derived from this file
#
######-------------------------------------------------------------------------------######

##-- Utilized by tiny-plot --##
# Filters for class scatter plots
plot_class_scatter_filter_include: []
plot_class_scatter_filter_exclude: []