######----------------------------- tinyRNA Configuration -----------------------------######
#
# In this file you may specify your configuration preferences for the workflow and
# each workflow step.
#
# If you want to use DEFAULT settings for the workflow, all you need to do is provide the path
# to your Samples Sheet and Features Sheet in your Paths file, then make sure that the
# 'paths_config' setting below points to your Paths file.
#
# We suggest that you also:
#   1. Add a username to identify the person performing runs, if desired for record keeping
#   2. Add a run directory name in your Paths file. If not provided, "run_directory" is used
#   3. Add a run name to label your run directory and run-specific summary reports.
#      If not provided, user_tinyrna will be used.
#
# This file will be further processed at run time to generate the appropriate pipeline
# settings for each workflow step. A copy of this processed configuration will be stored
# in your run directory (as specified by your Paths configuration file).
#
######-------------------------------------------------------------------------------######

user: NewUser
run_date: ~
run_time: ~
paths_config: ./paths.yml

##-- The label for final outputs --##
##-- If none provided, the default of user_tinyrna will be used --##
run_name: tinyrna

##-- If True: run bowtie-build before analyzing libraries --##
##-- NOTE: this option may be ignored depending on your Paths file. See Paths file. --##
run_bowtie_build: True

##-- Number of threads to use when a step supports multi-threading --##
##-- For best performance, this should be equal to your computer's processor core count --##
threads: 4

##-- Control the amount of information printed to terminal: debug, normal, quiet --##
verbosity: normal

##-- If True: process fastp, tiny-collapse, and bowtie in parallel per-library --##
run_parallel: true

##-- (EXPERIMENTAL) If True: execute the pipeline using native cwltool Python --##
run_native: false

######------------------------- BOWTIE INDEX BUILD OPTIONS --------------------------######
#
# If you do not already have bowtie indexes, they can be built for you by setting
# run_bowtie_build (above) to true and adding your reference genome file(s) to your
# paths_config file.
#
# We have specified default parameters for small RNA data based on our own "best practices".
# You may change the parameters here.
#
######-------------------------------------------------------------------------------######


##-- SA is sampled every 2^offRate BWT chars (default: 5)
offrate: ~

##-- Convert Ns in reference to As --##
ntoa: false

##-- Don't build .3/.4.ebwt (packed reference) portion --##
noref: false

##-- Number of chars consumed in initial lookup (default: 10) --##
ftabchars: ~


######---------------------TRIMMING AND QUALITY FILTER OPTIONS ----------------------######
#
# We use the program fastp to perform: adapter trimming (req), quality filtering (on),
# and QC analysis for an output QC report. See https://github.com/OpenGene/fastp for more
# information on the fastp tool. We have limited the options available to those appropriate
# for small RNA sequencing data. If you require an addition option, create an issue on the
# pipeline github: https://github.com/MontgomeryLab/tinyrna
#
# We have specified default parameters for small RNA data based on our own "best practices".
# You may change the parameters here.
#
######-------------------------------------------------------------------------------######


##-- Adapter sequence to trim --##
adapter_sequence: 'auto'

##-- Minumum & maximum accepted lengths after trimming --##
length_required: 15
length_limit: 35

##-- Minimum average score for a read to pass quality filter --##
average_qual: 25

##-- Minimum phred score for a base to pass quality filter --##
qualified_quality_phred: 20

##-- Minimum % of bases that can be below minimum phred score (above) --##
unqualified_percent_limit: 10

##-- Minimum allowed number of bases --##
n_base_limit: 1

##-- Compression level for gzip output --##
compression: 4

###-- Unused optional inputs: Remove '#' in front to use --###
##-- Trim poly x tails of a given length --##
# trim_poly_x: false
# poly_x_min_len: 0

##-- Trim n bases from the front/tail of a read --##
# trim_front1: 0
# trim_tail1: 0

##-- Is the data phred 64? --##
# fp_phred64: False

##-- Turn on overrepresentation sampling analysis --##
# overrepresentation_sampling: 0
# overrepresentation_analysis: false

##-- If true: don't overwrite the files --##
# dont_overwrite: false

##-- If true: disable these options --##
# disable_quality_filtering: false
# disable_length_filtering: false
# disable_adapter_trimming: false


######--------------------------- READ COLLAPSER OPTIONS ----------------------------######
#
# We use a custom Python utility for collapsing duplicate reads.
# We recommend using the default (keep all reads, or threshold: 0).
# Sequences <= threshold will not be included in downstream steps.
# Trimming takes place prior to counting/collapsing.
#
# We have specified default parameters for small RNA data based on our own "best practices".
# You may change the parameters here.
#
######-------------------------------------------------------------------------------######

##-- Trim the specified number of bases from the 5' end of each sequence --##
5p_trim: 0

##-- Trim the specified number of bases from the 3' end of each sequence --##
3p_trim: 0

##-- Sequences with count <= threshold will be placed in a separate low_counts fasta --##
threshold: 0

##-- If True: outputs will be gzip compressed --##
compress: False


######-------------------------- BOWTIE ALIGNMENT OPTIONS ---------------------------######
#
# We use bowtie for read alignment to a genome.
#
# We have specified default parameters for small RNA data based on our own "best practices".
# You may change the parameters here.
#
######-------------------------------------------------------------------------------######


##-- Report end-to-end hits w/ <=v mismatches; ignore qualities --##
end_to_end: 0

##-- Report all alignments per read (much slower than low -k) --##
all_aln: True

##-- Seed for random number generator --##
seed: 0

##-- Suppress SAM records for unaligned reads --##
no_unal: True

##-- Use shared mem for index; many bowtie's can share --##
##-- Note: this requires further configuration of your OS --##
##-- http://bowtie-bio.sourceforge.net/manual.shtml#bowtie-options-shmem --##
shared_memory: False

###-- Unused option inputs: Remove '#' in front to use --###
##-- Hits are guaranteed best stratum, sorted; ties broken by quality --##
#best: False

##-- Hits in sub-optimal strata aren't reported (requires best, ^^^^) --##
#strata: False

##-- Max mismatches in seed (can be 0-3, default: -n 2) --##
#seedmms: 2

##-- Seed length for seedmms (default: 28) --##
#seedlen: 28

##-- Do not align to reverse-compliment reference --##
# norc: False

##-- Do not align to forward reference --##
# nofw: False

##-- Input quals are Phred+64 (same as --solexa1.3-quals) --##
# bt_phred64: False

##-- Report up to <int> good alignments per read (default: 1) --##
# k_aln

##-- Number of bases to trim from 5' or 3' end of reads --##
# trim5: 0
# trim3: 0

##-- Input quals are from GA Pipeline ver. < 1.3 --##
# solexa: false

##-- Input quals are from GA Pipeline ver. >= 1.3 --##
# solexa13: false


######--------------------------- FEATURE COUNTER OPTIONS ---------------------------######
#
# We use a custom Python utility that utilizes HTSeq's Genomic Array of Sets and GFF reader
# to count small RNA reads. Selection rules are defined in your Features Sheet.
#
######-------------------------------------------------------------------------------######


##-- If True: show all parsed features in the counts csv, regardless of count/identity --##
counter_all_features: False

##-- If True: counts will be normalized by genomic hits AND selected feature count --##
##-- If False: counts will only be normalized by genomic hits --##
counter_normalize_by_hits: True

##-- If True: a decollapsed copy of each SAM file will be produced (useful for IGV) --##
counter_decollapse: False

##-- Only parse GFF lines that match these values on column 2. [] is wildcard --##
counter_source_filter: []

##-- Only parse GFF lines that match these values on column 3. [] is wildcard --##
##-- If source AND type filters are given, a line must match both to be included --##
counter_type_filter: []

##-- Select the StepVector implementation that is used. Options: HTSeq or Cython --##
counter_stepvector: 'Cython'

##-- If False: a feature with multiple values in its ID attribute is treated as an error --##
##-- If True: multiple ID values are allowed, but only the first value is used --##
counter_allow_multi_id: True

##-- If True: produce diagnostic logs to indicate what was eliminated and why --##
counter_diags: False


######--------------------------- DIFFERENTIAL EXPRESSION ---------------------------######
#
# Differential expression analysis is performed using the DESeq2 R library.
#
######-------------------------------------------------------------------------------######


##-- If True: produce a principal component analysis plot from the input dataset --##
dge_pca_plot: True

##-- If True: before analysis, drop features which have a zero count across all samples --##
dge_drop_zero: False


######-------------------------------- PLOTTING OPTIONS -----------------------------######
#
# We use a custom Python script for creating all plots. The default base style is called
# 'smrna-light'. If you wish to use another matplotlib stylesheet you may specify that in
# the Paths File.
#
# We have specified default parameters for small RNA data based on our own "best practices".
# You may change the parameters here.
#
######-------------------------------------------------------------------------------######


##-- Enable plots by uncommenting (removing the '#') for the desired plot type --##
##-- Disable plots by commenting (adding a '#') for the undesired plot type --##
plot_requests:
  - 'len_dist'
  - 'rule_charts'
  - 'class_charts'
  - 'replicate_scatter'
  - 'sample_avg_scatter_by_dge'
  - 'sample_avg_scatter_by_dge_class'

##-- You can set a custom P value to use in DGE scatter plots. Default: 0.05 --##
plot_pval: ~

##-- If True: scatter plot points will be vectorized. If False, only points are raster --##
plot_vector_points: False

##-- Optionally set the min and/or max lengths for len_dist plots; auto if unset --##
plot_len_dist_min:
plot_len_dist_max:


######----------------------------- OUTPUT DIRECTORIES ------------------------------######
#
# Outputs for each step are organized into their own subdirectories in your run
# directory. You may set these folder names here.
#
######-------------------------------------------------------------------------------######


dir_name_bt_build: bowtie-build
dir_name_fastp: fastp
dir_name_collapser: collapser
dir_name_bowtie: bowtie
dir_name_counter: counter
dir_name_dge: DGE
dir_name_plotter: plots


#########################  AUTOMATICALLY GENERATED CONFIGURATIONS #########################
#
# Do not make any changes to the following sections. These options are automatically
# generated using your Paths file, your Samples and Features sheets, and the above
# settings in this file.
#
###########################################################################################


######--------------------------- DERIVED FROM PATHS SHEET --------------------------######
#
# The following configuration settings are automatically derived from the sample sheet
#
######-------------------------------------------------------------------------------######

run_directory: ~
tmp_directory: ~
features_csv: { }
samples_csv: { }
reference_genome_files: [ ]
plot_style_sheet: ~
adapter_fasta: ~
ebwt: ~


######-------------------------- DERIVED FROM SAMPLE SHEET --------------------------######
#
# The following configuration settings are automatically derived from the sample sheet
#
######-------------------------------------------------------------------------------######

##-- Utilized by fastp, tiny-collapse, and bowtie --##
sample_basenames: [ ]

##-- Utilized by fastp --##
# input fastq files
in_fq: [ ]
# output reports
fastp_report_titles: [ ]

###-- Utilized by bowtie --###
# bowtie index files
bt_index_files: [ ]

##-- Utilized by tiny-deseq.r --##
# The control for comparison. If unspecified, all comparisons are made
control_condition:
# If the experiment design yields less than one degree of freedom, tiny-deseq.r is skipped
run_deseq: True

######------------------------- DERIVED FROM FEATURES SHEET -------------------------######
#
# The following configuration settings are automatically derived from the sample sheet
#
######-------------------------------------------------------------------------------######

###-- Utilized by tiny-count --###
# a list of only unique GFF files
gff_files: [ ]