######----------------------------- AQuATx Configuration -----------------------------######
#
# For reproducibility purposes, if you do not rename this file, we will make a copy
# with current run time and date information. 
# 
# Please rename this file with identifying information for provenance.
# If you would like to add run time information, you may add it here.
#
#
# 1. Add a username here to identify the person creating the runs, if desired for record keeping
# 2. Please add a final run directory to store files - otherwise it will be generated based on
#    initial run time and date (with added option username). 
# 3. Please add a final run output prefix to label run-specific summary reports - otherwise
#    it will be generated based on initial run time and date (with added optional username).
#
######-------------------------------------------------------------------------------######

user: ~
run_prefix: ~
run_date: ~
run_time: ~

paths_config:
  path: '../../START_HERE/paths.yml'
  class: File

##-- Final output file prefixes for overall run --##
##-- If none given, run_prefix is used (default: date_time_aquatx) --##
output_prefix: ~

##-- Set to True and provide a reference genome .fa file to index the genome --##
run_idx: False
reference_genome: ~

##-- Number of threads for multi-threaded programs --##
threads: 2


######---------------------TRIMMING AND QUALITY FILTER OPTIONS ----------------------######
#
# We use the program fastp to perform: adapter trimming (req), quality filtering (on), 
# and QC analysis for an output QC report. See https://github.com/OpenGene/fastp for more
# information on the fastp tool. We have limited the options available to those appropriate
# for small RNA sequencing data. If you require an addition option, create an issue on the
# pipeline github: https://github.com/biokcb/smallRNA/issues
# 
# We have specified default parameters for small RNA data based on our own "best practices".
# You may change the parameters here.
#
######-------------------------------------------------------------------------------######


##-- Adapter sequence to trim --##
adapter_sequence: 'auto'
 
##-- Minumum & maximum accepted lengths after trimming --##
length_required: 15
length_limit: 30

##-- Minimum phred score for a base to pass quality filter --##
qualified_quality_phred: 15

##-- Minimum % of bases that can be below minimum phred score (above) --##
unqualified_percent_limit: 0

##-- Minimum allowed number of bases --##
n_base_limit: 1

##-- Compression level for gzip output --##
compression: 4

###-- Unused option inputs: Remove '#' in front to use --###
##-- Trim poly x tails of a given length --##
#trim_poly_x: false
#poly_x_min_len: 0

##-- Is the data phred 64? --##
#fp_phred64: False

##-- Turn on overrepresentation sampling analysis --##
#overrepresentation_sampling: 0 
#overrepresentation_analysis: false

##-- If true: don't overwrite the files --##
#dont_overwrite: false

##-- If true: disable these options --##
#disable_quality_filtering: false
#disable_length_filtering: false
#disable_adapter_trimming: false


######--------------------------- READ COLLAPSER OPTIONS ----------------------------######
#
# We use a custom Python script for collapsing duplicate reads for now. There are only a 
# couple options and we recommend using the default (keep all reads: threshold = 0).
#
# We have specified default parameters for small RNA data based on our own "best practices".
# You may change the parameters here.
#
######-------------------------------------------------------------------------------######


##-- Sequences with count <= threshold will be placed in a separate low_counts fasta --##
threshold: 0

##-- If True: outputs will be gzip compressed --##
compress: False


######------------------------- BOWTIE2 ALIGNMENT OPTIONS ---------------------------######
#
# We use bowtie2 for read alignment to a genome. 
#
# We have specified default parameters for small RNA data based on our own "best practices".
# You may change the parameters here.
#
######-------------------------------------------------------------------------------######


##-- Max allowed num of mismatches --##
end_to_end: 0

##-- If True: report all alignments --##
all_aln: True

##-- Set a random seed for alignment --##
seed: 0

##-- If True: supress sam records for unaligned reads --##
no_unal: True

##-- If True: input files are fasta --##
fasta: True

##-- If True: output a sam file instead of stdout --##
sam: True

##-- If True: use shared mem for index; many bowtie's can share --##
shared_memory: True

###-- Unused option inputs: Remove '#' in front to use --###
##-- If true: do not align to reverse-compliment reference --##
#norc: False

##-- If True: do not align to forward reference --##
#nofw: False

##-- If True: input quality scores are Phred64 --##
#bt_phred64: False

##-- If True: input files are fastq --##
#fastq: False

##-- Number of alignments to report --##
#k_aln

##-- Number of bases to trim from 5' or 3' end of reads --##
#trim5: 0
#trim3: 0

##-- If True: input files are solexa or solexa 1.3 quality --##
#solexa: false
#solexa13: false


######--------------------------- FEATURE COUNTER OPTIONS ---------------------------######
#
# We use a custom Python script that utilizes the HTSeq API to count small RNA reads. 
#
#
######-------------------------------------------------------------------------------######

##-- If True: save intermediate table for each library with all alignment information --##
intermed_file: False


######---------------------- NORMALIZATION AND STATISTICS OPTIONS -------------------######
#
# We use a custom Python script for read normalization and statistical analysis 
# (differential gene expression) based on statistical methods developed in [ref]. If you 
# do not want to use this method and would prefer to use a method such as DESeq2 in R,
# set use_smrna_stats to False and your output will end at the counts step.
#
# We have specified default parameters for small RNA data based on our own "best practices".
# You may change the parameters here.
#
######-------------------------------------------------------------------------------######

##-- If True: use zero-inflated model for normalization and DEG calling --##
use_smrna_stats: False
use_deseq: True


#########################  AUTOMATICALLY GENERATED CONFIGURATIONS #########################
#
# These options are automatically generated using features.csv, samples.csv, paths.yml,
# and the above settings in this file.
#
###########################################################################################


samples_csv:
  class: File

features_csv:
  class: File

ebwt: ''


######-------------------------- DERIVED FROM SAMPLE SHEET --------------------------######
#
# The following configuration settings are automatically derived from the sample sheet
#
######-------------------------------------------------------------------------------######

# input fastq files
in_fq: [ ]
# output, cleaned fastq files
out_fq: [ ]
# output reports
report_title: [ ]
# html report filenames
html: [ ]
# json report filenames
json: [ ]

##-- Utilized by Collapser --##
# prefix to be used for output file (files, if non-zero threshold)
uniq_seq_prefix: [ ]

###-- Utilized by Bowtie --###
# bowtie index files
bt_index_files: [ ]
# output alignment file names
outfile: [ ]
#unaligned read file names
un: [ ]

######------------------------- DERIVED FROM FEATURES SHEET -------------------------######
#
# The following configuration settings are automatically derived from the sample sheet
#
######-------------------------------------------------------------------------------######

###-- Utilized by Counter --###
# a list of only unique GFF files
gff_files: [ ]