name: tinyrna
channels:
  - bioconda
  - main
dependencies:
  - python>=3.9
  - bioconductor-deseq2==1.34.0
  - bowtie==1.3.1
  - fastp==0.23.2
  - htseq==2.0.2
  - nodejs==16.13.1
  - numpy==1.23.1
  - pandas==1.4.3
  - pip==22.1.2
  - setuptools==63.1.0
  - conda-forge::cwltool==3.1.20220628170238
  - conda-forge::matplotlib==3.5.2
  - conda-forge::mscorefonts==0.0.1
  - conda-forge::psutil==5.9.1
  - conda-forge::r-base==4.1.1
  - pip:
    - ../ # Install tinyRNA via setup.py
variables:
  - PYTHONNOUSERSITE: 1