name: tinyrna
channels:
- bioconda
- main
dependencies:
- python>=3.10, <3.11
- pysam>=0.21.0    # 0.20 is incompatible with Apple Silicon. This is likely safe to remove in the future
- bioconductor-deseq2=1.38.0
- bowtie=1.3.1
- cython=0.29.35
- fastp=0.23.4
- htseq=2.0.3
- nodejs=16.19.0
- pandas=2.0.2
- pip=23.1.2
- setuptools=67.8.0
- conda-forge::cwltool=3.1.20230601100705
- conda-forge::cxx-compiler=1.5.2
- conda-forge::matplotlib=3.7.1
- conda-forge::numpy=1.24.3
- conda-forge::mscorefonts=0.0.1
- conda-forge::psutil=5.9.5
- conda-forge::r-base=4.2.3
- conda-forge::urllib3 <2  # Mamba solves for a bad build of cwl-utils which didn't state its requirement for urllib3 <2 (likely temporary)
variables:
- PYTHONNOUSERSITE: 1

# tinyRNA codebase must be installed via pip in root project dir
