name: Unit Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "ubuntu-latest" ]
        python-version: [ "3.7" ]

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Setup Conda environment
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true
          activate-environment: tinyrna
          environment-file: environment.yml
          auto-activate-base: false
      - name: Run tests
        shell: bash -l {0}
        working-directory: ./tests
        run: |
          python -m unittest unit_tests_collapser
          python -m unittest unit_tests_entry
          python -m unittest unit_tests_counter
          python -m unittest unit_tests_features
          python -m unittest unit_tests_hts_parsing
